[settings]
repeat = 1

[base_config]
description = "Base Configuration Defaults"
run = false
baseline = false

[base_config.args]
model = "/mnt/data/gguf/DeepSeek-R1-Q4_K_M.gguf"
# model = "/mnt/data/gguf/qwen2.5-0.5b-instruct-q4_k_m.gguf"
prompt = "Please help me write a paragraph introducing Beijing."
n-predict = 100
ctx-size = 1024
n-gpu-layers = 0
seed = 0
override-tensor = ""

[[configs]]
description = "No offload to GPU"
run = true
[configs.args]

[[configs]]
description = "Offload 2 layers"
run = true
baseline = true
[configs.args]
n-gpu-layers = 2

[[configs]]
description = "Offload 10 layers, override exps=CPU"
run = true
[configs.args]
n-gpu-layers = 10
override-tensor = "exps=CPU"

[[configs]]
description = "Offload 20 layers, override exps=CPU"
run = true
[configs.args]
n-gpu-layers = 20
override-tensor = "exps=CPU"

[[configs]]
description = "Offload 30 layers, override exps=CPU"
run = true
[configs.args]
n-gpu-layers = 30
override-tensor = "exps=CPU"

[[configs]]
description = "Offload 40 layers, override exps=CPU"
run = true
[configs.args]
n-gpu-layers = 40
override-tensor = "exps=CPU"

[[configs]]
description = "Offload all layers, override exps=CPU"
run = true
[configs.args]
n-gpu-layers = 999
override-tensor = "exps=CPU"
